# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:23-alpine

# Create app directory
WORKDIR /app

# Copy package and source
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies and tools
RUN apk add --no-cache python3 make g++ git \
    && npm install \
    && npm install -g ts-node typescript \
    && apk del python3 make g++

# Expose no ports (stdio communication)

CMD ["ts-node", "src/main.ts"]
